spring:
  application:
    name: zipkin-server
server:
  port: 9100
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://user:passw0rd@127.0.0.1:2100/eureka
management:
  metrics:
    web:
      server:
        auto-time-requests: false